############# HOOKS ########################

# add lines numbers
hook global WinCreate .* %{addhl number_lines}

# add brackets highliting
hook global WinCreate .* %{addhl show_matching}

# use only spaces do not use tabs
hook -group TabExpander global InsertChar \t %{ exec -draft h@}

# Add autowrap to 72 characters in git-commit
hook -group GitWrapper global WinSetOption filetype=git-commit %{
    set buffer autowrap_column 72
    autowrap-enable

    hook window WinSetOption filetype=(?!git-commit).* %{ autowrap-disable }
}

hook -group PythonJediAutostart global WinSetOption filetype=python %{
    jedi-enable-autocomplete
}

hook global WinSetOption filetype=(?!python).* %{
    jedi-disable-autocomplete
}

# Add our special .ks.in files as normal Kickstart
hook global WinCreate .*\.ks\.in %{
    set buffer filetype kickstart
}

# show all trailing whispaces red
hook -group TrailingWhitespaces global WinCreate .* %{
    addhl regex '\h+$' 0:default,red
}

#################################

set global tabstop 4

map global user n ':eval %{buffer-next}<ret>' -docstring "Switch to next buffer"
map global user b ':eval %{buffer-previous}<ret>' -docstring "Switch to previous buffer"

# yank and paste to/from external clipboard
map global user y '<a-|>xsel -b <ret>:echo -markup {Information}"Yanked to clipboard"<ret>' -docstring "Copy to clipboard"
map global user p '<a-!>xsel -b -o<ret>:echo -markup {Information}"Pasted from clipboard"<ret>' -docstring "Paste from clipboard"

map global user h ':doc shortcuts<ret>' -docstring "Show keymapping help"

# yank to system clipboard always
hook global NormalKey y|d|c %{ nop %sh{
   echo "$kak_selection" | xsel
}}

# write pdb to this row
map global user d '<esc>oimport pdb; pdb.set_trace()<esc>' -docstring "Inser Python's pdb to to line below this line"

# select all occurrences in this buffer
map global user a '*%s<c-/><ret>' -docstring "Select all occurrences of this word in the buffer"

# Quickly run compile-pdf
map global user c ':compile-pdf<ret>' -docstring "Quickly run compile-pdf"

# my personal functions
def push_kickstart -docstring "Push actual buffer to cobra02" %{
write
%sh{
    /home/jkonecny/RH/scripts/vm_scripts/push_kickstart.sh "$kak_buffile" > /dev/null

    if [ $? -eq 0 ]; then
        echo "echo -markup {Information} KS $kak_bufname pushed successful"
    else
        echo "echo -markup {Error} Push failed"
    fi
}}

# Compile ReST or Doctext to pdf
def compile-pdf -docstring "Compile output doctext or rest to name.pdf" %{
write
%sh{
    pandoc -s -o ${kak_bufname%%.*}.pdf $kak_bufname

    if [ $? -eq 0 ]; then
        echo "echo -markup {Information}Conversion to pdf was successful"
    else
        echo "echo -markup {Error}Compilationfailed"
    fi
}}


# easy way how to hide incorrect spelling highlighter
def hide-spell -docstring "Hide spell correction" %{
    remove-highlighter hlranges_spell_regions
}


###############################
# Testing stuff

hook global WinSetOption filetype=python %{

    def pylint_test -docstring "Test active buffer with pylint - python static checker utility" %{
       %sh{
            pylint=$(which pylint)
            if [ -z $pylint ]; then
                echo "echo -markup {red}'You don't have pylint installed!'"
                exit 1
            fi
            #if [ -f $kak_buffile ]; then
            #    TEMP=$(mktemp pylint-test.XXXXXXX)
            #fi
            out_fifo=$(mktemp -d -t kak-pylint.XXXXXXXX)/fifo
            mkfifo ${out_fifo}
            ( $pylint --reports=n $kak_buffile > $out_fifo 2>&1 ) > /dev/null 2>&1 < /dev/null &

            printf %s "eval -client '$kak_client' %{
                      edit! -fifo ${out_fifo} *pylint*
                      hook -group pylint_fifo buffer BufCloseFifo .* %{
                          nop %sh{ rm -r $(dirname ${out_fifo}) }
                          rmhooks buffer pylint_fifo
                      }
                  }"
        }
    }
}
